### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by typiconman** [slavonic/odt2md#4]
The odt2md conversion puts additional line breaks (see enclosed files, after мольба́ми, and after ꙗ҆́кѡ да).
Is this a bug or a feature?

[testconv.zip](https://github.com/slavonic/odt2md/files/4393598/testconv.zip)
[testconv.odt.zip](https://github.com/slavonic/odt2md/files/4393609/testconv.odt.zip)

**Comment by pgmmpk** [comment]
It's a feature. Converter breaks long lines to fit the standard screen width (128? 80?).

Line breaks in Markdown are insignificant (like in LaTeX). Paragraph breaks are indicated by and
empty line (again, similar to LaTeX).

Is this causing any problem?

**Comment by typiconman** [comment]
I find it a bit annoying. In VS Code, the syntax markup only displays correctly if the opening and closing = = and + + are on the same line.

**Comment by typiconman** [comment]
I must have a non-standard screen width, because it looks weird here.
![Screenshot from 2020-03-28 21-10-48](https://user-images.githubusercontent.com/5428695/77830354-ec9c6080-7138-11ea-9a42-ba7056b79e70.png)

**Comment by pgmmpk** [comment]
In version 0.0.6 two changes:

1. Default line breaking width increased from 100 to 128 (to better match my editor)
2. It can be adjusted using `--max_line_width/-m` flag, if needed.

If it is desirable to avoid any line breaks, set it to `10000`. 

Your screen seem to use rather large font and hence is probably limited to the classic 80-char width.

**Comment by typiconman** [comment]
Yes, it works. Thanks!
