### ISSUE TITLE
odt2md ignores sections

### ISSUE THREAD

**Issue by typiconman** [slavonic/odt2md#5]
Any text or images placed in a section is ignored.
The workaround for that is to get rid of sections in the ODT document: (in LibreOffice) Format -> Sections -> Remove.

**Comment by pgmmpk** [comment]
Sounds like a bug. Could you give me a simple *.odt file showing this missing text/images?

**Comment by typiconman** [comment]
Please see attached.
[example.odt.zip](https://github.com/slavonic/odt2md/files/4397147/example.odt.zip)
[example.zip](https://github.com/slavonic/odt2md/files/4397149/example.zip)

**Comment by pgmmpk** [comment]
Fixed in version 0.0.5. Please, update

**Comment by typiconman** [comment]
It works, thanks.
